# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html

security:

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN , ROLE_ALLOWED_TO_SWITCH]

    encoders:
#        Core\UserBundle\Entity\User:
        Vinologie\UserBundle\Entity\User:
            algorithm: sha512
            iterations: 200
            encode_as_base64: true

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        my_bdd:
            entity:
#                class: Core\UserBundle\Entity\User
                class: Vinologie\UserBundle\Entity\User
                property: username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs


        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: true
            form_login:
                login_path: login
                check_path: login_check
                default_target_path: /myaccount/dashboard
            logout:
                path:   /logout


