Vinologie\ServiceBundle\Entity\Degustation:
    properties:
        hours:
            - DateTime: ~
            - NotBlank: ~
        description:
            - Type: string
            - Length:
                min: 3
                max: 500
            - NotBlank: ~
        maxGuestNumber:
            - Type: integer
            - Range:
                min: 0
                max: 50
        address: ~