services:
#    vinologie_service.example:
#        class: Vinologie\ServiceBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]

    vinologie_service_degustation_subscription:
        class: Vinologie\ServiceBundle\Service\DegustationSubscriptionService
        arguments: [ "@doctrine.orm.entity_manager" , "@event_dispatcher" ]

    vinologie_service_guest_list:
        class: Vinologie\ServiceBundle\Service\GuestListService
        arguments: [ "@doctrine.orm.entity_manager" ]


    asi_advert.advert_type_extension:
        class: Vinologie\ServiceBundle\TwigExtension\DegustationTypeExtension
        public: false
        tags:
            - { name: twig.extension }
        arguments:
            - "@vinologie_service_guest_list"