Vinologie\UtilsBundle\Entity\UserRichResource:
    type: mappedSuperclass
    manyToOne:
        createdBy:
            targetEntity: Vinologie\UserBundle\Entity\User
            joinColumn:
                name: user_id
                referencedColumnName: uid



